
name: Add label to PR on comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify the person
        id: verify_member
        uses: ./.github/actions/verifyMember
        with:
          authorName: "${{github.event.comment.user.login}}"

      - name: Add the vote label and handle unauthorized attempts
        if: contains(github.event.comment.body, '/vote') && steps.verify_member.outputs.output_name == 'true'
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "vote"
          else
            gh issue edit ${{ github.event.issue.number }} --add-label "vote"
          fi

          # Send unauthorized attempt message if the user is not authorized and not the 'git-vote[bot]'
          if [ "${{ steps.verify_member.outputs.isTSCMember }}" != "true" ] && [ "${{ github.actor }}" != "git-vote[bot]" ] && contains(github.event.comment.body, '/vote'); then
            const commentText = `❌ @${{github.actor}} is not authorized to vote.
            These commands can only be used by members of the [Bounty Team](https://github.com/orgs/asyncapi/teams/bounty_team).`;

            console.log(`❌ @${{github.actor}} made an unauthorized attempt to use a Bounty Program's command.`);
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentText
              })
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
