name: Process Votes

on:
  issue_comment:
    types: [created]

jobs:
  process-vote:
    runs-on: ubuntu-latest
    steps:
      - name: Check if vote comment
        id: check-vote
        run: echo "${{ github.event.comment.body }}" | grep -q '/vote'
      - name: Add vote label
        if: steps.check-vote.outputs.result == 'true' && github.event.comment.author_association == 'MEMBER' # Add conditions for authorized voters
        run: |
          echo "Adding vote label..."
          echo "::set-env name=ISSUE_NUMBER::${{ github.event.issue.number }}"
          echo "vote-label" >> labels.txt
          echo "Added vote label successfully."
      - name: Get issue number
        if: steps.check-vote.outputs.result == 'true' && github.event.comment.author_association == 'MEMBER' # Add conditions for authorized voters
        id: get-issue-number
        run: echo "::set-output name=issue_number::${{ steps.process-vote.outputs.ISSUE_NUMBER }}"
      - name: Add label
        if: steps.check-vote.outputs.result == 'true' && github.event.comment.author_association == 'MEMBER' # Add conditions for authorized voters
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = "${{ steps.get-issue-number.outputs.issue_number }}";
            const labelsToAdd = fs.readFileSync('labels.txt', 'utf8').trim().split('\n');
            await github.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: labelsToAdd
            });
