name: Add label to PR on comment

on:
  issue_comment:
    types: [created]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the comment author and body
        id: get_comment_info
        run: |
          echo "Comment author: ${{ github.event.comment.user.login }}"
          echo "Comment body: ${{ github.event.comment.body }}"

      - name: Add the label
        if:  steps.get_comment_info.outputs.author == 'git-vote[bot]' 
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "vote"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: vote
