name: Add label to PR on comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the comment body
        id: get_comment_body
        run: |
          echo "Comment body: ${{ github.event.comment.body }}"
      
      - name: Add the label
        if: contains(github.event.comment.body, '/vote') && github.event.comment.user.login == 'AayushSaini101'
        run: gh issue edit ${{ github.event.issue.number }} --add-label "vote"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
