name: Process Votes

on:
  issue_comment:
    types: [created]

jobs:
  process-vote:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if vote comment
        id: check-vote
        run: echo "${{ github.event.comment.body }}" | grep -q 'Vote created'
      - name: Add vote label
        if: steps.check-vote.outputs.result == 'true' # Add conditions for authorized voters
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
        run: gh issue edit $NUMBER --add-label $LABELS