name: Add label to PR on comment

on:
  issue_comment:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the comment body
        id: get_comment_body
        run: |
          echo "Comment body: ${{ github.event.comment.body }}" | ls

      - name: Verify TSC Member
        id: verify_member
        uses: actions/github-script@v6
        with:
         script: |
          const fs = require('fs');
          const filePath = '../../users.json';
          const commenterName = context.payload.sender.login
          let isTSCMember = false;
          fs.readFile(filePath, 'utf8', (err, data) => {
            try {
 
           const jsonData = JSON.parse(data);
  
           // Iterate over each object in the array
             jsonData.forEach(item => {
                if(item.github === commenterName){
                    isTSCMember=true
                 }
             });
           } catch (parseError) {
               
           }
          });
          console.log('Is TSC Member:', isTSCMember);
          core.setOutput('isTSCMember', isTSCMember);
          console.log('commentername',commenterName);


      - name: Add the label
        if: contains(github.event.comment.body, '/vote') && steps.verify_member.isTSCMember == true
        run: gh issue edit ${{ github.event.issue.number }} --add-label "vote"
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NAME: 'AayushSaini101'
