name: Process Votes

on:
  issue_comment:
    types: [created]

jobs:
  process-vote:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if vote comment
        id: check-vote
        run: echo "${{ github.event.comment.body }}" | grep  "Vote created"
      - name: Add vote label
        if: steps.check-vote.outputs.result == 'true' # Add conditions for authorized voters
        run: |
          gh issue add-label --issue ${{ github.event.issue.number }} --label "needs-more-info"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
