name: Remove vote label

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Verify the person
        uses: ./.github/actions/verifyMember
        with:
          authorName: "${{github.event.comment.user.login}}"

      - name: Add the label
        if: contains(github.event.comment.body, '/cancel-vote') && steps.verify_member.outputs.isTSCMember =='true'
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --remove-label "vote"
          else
            gh issue edit ${{ github.event.issue.number }} --remove-label "vote"
          fi

          # Send message if the member is not authorized
          if [ "${{ steps.verify_member.outputs.isTSCMember }}" != "true" ]; then
            echo "Unauthorized member. Cannot remove label."
            # Add your message sending logic here, for example:
            # echo "You are not authorized to perform this action."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}