name: Remove vote label

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the comment body
        id: get_comment_body
        run: |
          echo "Comment body: ${{ github.event.comment.body }}"

      - name: Verify TSC Member
        id: verify_member
        uses: vote/.github/workflows/verify


      - name: Add the label
        if: contains(github.event.comment.body, '/cancel-vote') && steps.verify_member.outputs.isTSCMember =='true'
        run: |
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              gh pr edit ${{ github.event.pull_request.number }} --remove-label "vote"
            else
              gh issue edit ${{ github.event.issue.number }} --remove-label "vote"
            fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

