name: 'Verify TSC Member'
description: 'Verifies whether the commenter is a TSC member.'

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    using: "composite"
    steps:
      - name: Verify TSC Member
        id: verify_member
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const filePath = 'users.json';
            const commenterName = context.payload.sender.login;
            let isTSCMember = false;
            
            function readFileAndProcess(callback) {
              fs.readFile(filePath, 'utf8', (err, data) => {
                if (err) {
                  callback(err, null);
                  return;
                }
                try {
                  const jsonData = JSON.parse(data);
                  // Iterate over each object in the array
                  jsonData.forEach(item => {
                    if (item.github === commenterName) {
                      isTSCMember = true;
                    }
                  });
                  // Invoke the callback function with the result
                  callback(null, isTSCMember);
                } catch (parseError) {
                  callback(parseError, null);
                }
              });
            }
            
            readFileAndProcess((error, result) => {
              if (error) {
                console.error('Error:', error);
              } else {
                console.log('Is TSC Member:', result);
                core.setOutput('isTSCMember', isTSCMember);
              }
            });