name: Vote Tracker

on:
  issue_comment:
    types: [created]

jobs:
  track-vote:
    if: ${{ github.actor == 'git-vote[bot]' && contains(github.event.comment.body, 'Vote closed')}}
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing Module
        run: npm install js-yaml@4.1.0
        shell: bash

      - name: Run GitHub Script
        id: vote_tracker
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/vote_tracker.js');
            await script({ github, context, core });

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit VotingTracking.json
        run: |
          git add voteTrackingDetails.md VoteTracking.json
          git commit -m "Update vote tracking details"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}