name: Vote Tracker

on:
  issue_comment:
    types: [created]

jobs:
  track-vote:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Debug Environment Variables
      - name: Debug Environment Variables
        run: |
          echo "User: ${{ github.event.comment.user.login }}"
          echo "Comment Body: ${{ github.event.comment.body }}"

      # Run vote tracker script
      - name: Run vote tracker script
        if: |
          github.event.comment.user.login == 'git-vote[bot]' &&
          contains(github.event.comment.body, 'Vote closed')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: node .github/scripts/vote_tracker.js

      - name: Upload binding votes JSON
        uses: actions/upload-artifact@v2
        with:
          name: binding-votes
          path: bindingVotes.json
